version: '3'

services:
  api:
    build: 
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: