name: CD Pipeline

on:
  push:
    branches: [ "refactor/service" ]

jobs:
  deploy:
    runs-on: oracle
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          clean: true

      - name: set up docker compose
        run: |
          docker compose up --build -d --remove-orphans
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: API server health check
        run: |
          sleep 5
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
          
          if [ $response_code -eq 200 ]; then
            echo "API server is healthy (HTTP $response_code)"
          else
            echo "API server is not healthy (HTTP $response_code)"
            exit 1
          fi

secrets:
  DB_PASSWORD: 
    description: 'Database password'
    required: true
