name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linting
        run: flake8 .
